### ISSUE TITLE
installing `Graphical-Module`

### ISSUE THREAD

**Issue by prko** [SimonDeplat/Graphical-Module#1]
To install it, I had to use the following code:
Quarks.install("https://github.com/SimonDeplat/Graphical-Module")

--
Sorry, I should have posted it on https://github.com/SimonDeplat/Metronome/issues

**Comment by SimonDeplat** [comment]
Thank you for your feedback :) !

I think that's the right place to post the issue.

I messed up a bit with the Quark name, there was a space in the original name : "Graphical Module", which was replaced by "Graphical-Module" in the git version. But in the in the SuperCollider's quark interface, I named it "GraphicalModule", without any separation. Could it be the reason the install failed ?

`Quarks.install("GraphicalModule")` should work ? At least, on Ubuntu 22.04 LTS I was able to reinstall it after purging it.

`Quarks.install("Graphical-Module")` should **not** work because this isn't the name SC recognizes ?

If `Quarks.install("GraphicalModule")` still fails, do you have an error message ?

EDIT : did you update your Quark interface before trying to install it ? The Quark was released a week ago so maybe it was missing from the config file ?

Anyway I didn't know we could install Quarks by direct URL, which is a cool feature.

As a side note : if you plan to use Metronome, depending on when you downloaded it, there might be a missing empty folder called 'presets' within the project directory, preventing you from saving presets. I didn't know git would not accept empty directories, I fixed the issue since then but I don't know if you downloaded the project before I did.

**Comment by prko** [comment]
Um...

After evaluating the following code:
```
Quarks.all.do{|quark| quark.update() }
```
I reevaluated your code:
```
Quarks.install("GraphicalModule")
```
It returns the following error:
```
ERROR: Quark 'GraphicalModule' not found
CALL STACK:
	Exception:reportError
		arg this = <instance of Error>
	Nil:handleError
		arg this = nil
		arg error = <instance of Error>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of Error>
	Object:throw
		arg this = <instance of Error>
	Meta_Quark:new
		arg this = <instance of Meta_Quark>
		arg name = "GraphicalModule"
		arg refspec = nil
		arg url = nil
		arg localPath = nil
		var args = nil
	Meta_Quarks:install
		arg this = <instance of Meta_Quarks>
		arg name = "GraphicalModule"
		arg refspec = nil
		var path = nil
		var quark = nil
	Interpreter:interpretPrintCmdLine
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "Quarks.install("GraphicalMod..."
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Quark 'GraphicalModule' not found
```
Evaluating the following code:
```
Quarks.install("Graphical-Module")
```
returns the following error:
```
ERROR: Quark 'Graphical-Module' not found
CALL STACK:
	Exception:reportError
		arg this = <instance of Error>
	Nil:handleError
		arg this = nil
		arg error = <instance of Error>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of Error>
	Object:throw
		arg this = <instance of Error>
	Meta_Quark:new
		arg this = <instance of Meta_Quark>
		arg name = "Graphical-Module"
		arg refspec = nil
		arg url = nil
		arg localPath = nil
		var args = nil
	Meta_Quarks:install
		arg this = <instance of Meta_Quarks>
		arg name = "Graphical-Module"
		arg refspec = nil
		var path = nil
		var quark = nil
	Interpreter:interpretPrintCmdLine
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "Quarks.install("Graphical-Mo..."
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Quark 'Graphical-Module' not found
```
Please let me know if I did something wrong.

**Comment by prko** [comment]
Ah....

```
Quarks.all.do{|quark| quark.update() }
```
does not update `Platform.userAppSupportDir +/+ "downloaded-quarks/quarks/directory.txt"`.

And..., I do not know how to update this file. Could you help me?

**Comment by prko** [comment]
Oh, it was my fault.
I did not update `Platform.userAppSupportDir +/+ "downloaded-quarks/quarks/directory.txt"` by pressing  the `Check for update` button in Quark GUI. Sorry!
